### PR TITLE
Docker compose upgrade

### PR DESCRIPTION
**Pull request by Aaron-Ritter**
This is a upgrade test using the latest PostgreSQL release, switching to OpenSearch and adding a monthly dependabot check which addresses and tests the two issues reported:

https://github.com/FusionAuth/fusionauth-issues/issues/2520
https://github.com/FusionAuth/fusionauth-issues/issues/2521

I've chosen the fusiondesk example for testing because it creates multiple users and a more complex initial kickstart.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1205772976883825
  - https://app.asana.com/0/0/1205784264910475
  - https://app.asana.com/0/0/1205839140586436

### CODE REVIEW

**Comment by Aaron-Ritter** [comment]
@mooreds as discussed here an implementation test PR for an upgraded docker-compose.yml

**Review by mark-robustelli — CHANGES_REQUESTED** [review]
When I start the app, I do not get the login icon so I can't seem to test anything out.  I also,  do not get the Fusion Desk Logo. That may have more to do with the kickstart but not sure.

Is this expected?

Screenshot 2023-10-26 at 4 34 14 PM

**Comment by Aaron-Ritter** [comment]
In this repository the assets used in FusionAuth require https://github.com/FusionAuth/fusionauth-example-react-fusiondesk#server and https://github.com/FusionAuth/fusionauth-example-react-fusiondesk#client running.

**Review by mark-robustelli — APPROVED** [review]
I did test it out and looks good.

**Pull request merged**
